version: 1
formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "[%X]"
handlers:
  console:
    class: rich.logging.RichHandler
    level: NOTSET
    formatter: detailed
    markup: true
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: library.log
    maxBytes: 10485760 # 10 MB
    backupCount: 5
root:
  level: NOTSET
  handlers: [console, file]
